# Title of your website
title: "Trust CPS Group"

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "Researching trustworthy cyber-physical systems "

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Online-representation of the Trust CPS Group at TU Wien."

# The credits show up in the includes/_footer.html – It would be nice of you to leave a link to Phlow or Feeling Responsive as a thank you :)
credits: '<p>Created with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a>.</p>'

# Main author of the website
# See > authors.yml
author: Ezio Bartocci, Stefan Schupp

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: ""
baseurl: ""

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: #https://github.com/trust-cps-group/feeling-responsive/edit/gh-pages

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
#urlimg: "https://phlow.github.io/feeling-responsive/images/"
urlimg: "https://trust-cps-group.github.io/images/"

# Logo size is 600x80 pixels
logo: "images/group_pictures/trust_cps.png"

# Plugins
plugins:
  - jekyll-asciidoc
  - jekyll-gist
  - jekyll-paginate

# Pagination
paginate: 5 # Paginates all X entries
paginate_path: "blog/page:num" # Pagination path › Important for blog page in /blog/ to work

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
excerpt_separator: "<!--more-->"
include: [".htaccess"]
# Exclude these files from your production _site
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - INSTALL.md
  - vendor

# The language setting is used in /includes/header.html for html-settings
language: "en"

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

# Default Settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false # Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      # author: phlow # Default author for pages
  - scope:
      path: ""
      type: "posts"
    values:
      show_meta: true # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      # author: phlow # Default author for posts
  - scope:
      path: "pages/people"
      type: "pages"
    values:
      header: no
      layout: person-fullwidth
      categories: "people"
      prio: "0"
  - scope:
      path: "pages/alumni"
      type: "pages"
    values:
      header: no
      layout: page-fullwidth
      categories: "alumni"
  - scope:
      path: "pages/administrative"
      type: "pages"
    values:
      header: no
      layout: page-fullwidth
      categories: "administrative"
  - scope:
      path: "pages/research_projects"
      type: "pages"
    values:
      header: no
      layout: page-fullwidth
      categories: "research"


#  Open _data/navigation.yml to adjust the left and right topbar navigation
#

#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

#google_author: "https://plus.google.com/u/0/118311555303973066167"
#google_site_verification: "Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ"
#bing_webmastertools_id: "0FB4C028ABCF07C908C54386ABD2D97F"
# yandex_site_verification:  ''
# alexa_verify_id:           ''

#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32: "favicon-32x32.png"
touch-icon-192x192: "touch-icon-192x192.png"
apple-touch-icon-180x180-precomposed: "apple-touch-icon-180x180-precomposed.png"
apple-touch-icon-152x152-precomposed: "apple-touch-icon-152x152-precomposed.png"
apple-touch-icon-144x144-precomposed: "apple-touch-icon-144x144-precomposed.png"
apple-touch-icon-120x120-precomposed: "apple-touch-icon-120x120-precomposed.png"
apple-touch-icon-114x114-precomposed: "apple-touch-icon-114x114-precomposed.png"
apple-touch-icon-76x76-precomposed: "apple-touch-icon-76x76-precomposed.png"
apple-touch-icon-72x72-precomposed: "apple-touch-icon-72x72-precomposed.png"
apple-touch-icon-precomposed: "apple-touch-icon-precomposed.png"
msapplication_tileimage: "msapplication_tileimage.png" # Size 144x144
msapplication_tilecolor: "#fabb00"

#      _____            _       __   __  ___         ___
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ /
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/
#
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#

socialmedia:
  #twitter:
  #facebook:

#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

#sass:
#  sass_dir: _sass
#  style: :compressed

#       ___                __      __  _
#      /   |  ____  ____ _/ /_  __/ /_(_)_________
#     / /| | / __ \/ __ `/ / / / / __/ / ___/ ___/
#    / ___ |/ / / / /_/ / / /_/ / /_/ / /__(__  )
#   /_/  |_/_/ /_/\__,_/_/\__, /\__/_/\___/____/      https://www.google.com/analytics/
#                        /____/
#
# used in _includes/footer_scripts

# google_analytics_tracking_id:

#     ___              _     __           __
#    /   |  __________(_)___/ /___  _____/ /_____  _____
#   / /| | / ___/ ___/ / __  / __ \/ ___/ __/ __ \/ ___/
#  / ___ |(__  ) /__/ / /_/ / /_/ / /__/ /_/ /_/ / /
# /_/  |_/____/\___/_/\__,_/\____/\___/\__/\____/_/
#
#  Asciidoctor is a fast text processor and publishing toolchain for converting
#  AsciiDoc content to HTML5, DocBook 5 (or 4.5) and other formats.
#
#  https://github.com/asciidoctor/jekyll-asciidoc
#  https://github.com/asciidoctor
#
#

asciidoctor-enabled: false
asciidoctor:
  description:
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font

########### Jekyll scholar

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: year
  group_order: descending

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: single_reference

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
